#!/bin/bash
export POSIXLY_CORRECT=yes
#clear

########	HELP SECTION	########

help(){
	echo "Usage:	./corona [-h] [FILTERS] [COMMAND] [LOG [LOG2 [...]]]"
	echo ""

	echo "Popis:"
	echo "	Skript filtruje záznamy osob s prokázanou nákazou koronavirem způsobujícím onemocnění COVID-19. Pokud je skriptu zadán také příkaz, nad filtrovanými záznamy daný příkaz provede."
	echo "	Pokud skript nedostane ani filtr ani příkaz, opisuje záznamy na standardní výstup."
	echo "	Skript umí zpracovat i záznamy komprimované pomocí nástrojů gzip a bzip2 (v případě, že název souboru končí .gz resp. .bz2)."
	echo "	V případě, že skript na příkazové řádce nedostane soubory se záznamy (LOG, LOG2, …), očekává záznamy na standardním vstupu."
	echo "	Pokud má skript vypsat seznam, každá položka je vypsána na jeden řádek a pouze jednou. Není-li uvedeno jinak, je pořadí řádků dáno abecedně. Položky se nesmí opakovat."
	echo "	Grafy jsou vykresleny pomocí ASCII a jsou otočené doprava. Hodnota řádku je vyobrazena posloupností znaku mřížky #."
	echo ""

	echo "Návratová hodnota:"
	echo "	Skript vrací úspěch v případě úspěšné operace. Interní chyba skriptu nebo chybné argumenty budou doprovázeny chybovým hlášením na stderr a neúspěšným návratovým kódem."
	echo ""

	echo "Seznam dostupných přepínačů:"
	echo ""
	echo "	-a DATETIME		Jsou uvažovány pouze záznamy po tomto datu (včetně tohoto data). DATETIME je formátu YYYY-MM-DD"
	echo "	-b DATETIME		Jsou uvažovány pouze záznamy PŘED tímto datem (včetně tohoto data)"
	echo "	-g GENDER		Jsou uvažovány pouze záznamy nakažených osob daného pohlaví. GENDER může být M (muži) nebo Z (ženy)"
	echo "	-h			Vypíše nápovědu s krátkým popisem každého příkazu a přepínače"
	echo "	-s [WIDTH]		U příkazů gender, age, daily, monthly, yearly, countries, districts a regions vypisuje data ne číselně, ale graficky v podobě histogramů."
	echo "				Nepovinný parametr WIDTH nastavuje šířku histogramů, tedy délku nejdelšího řádku, na WIDTH. Tedy, WIDTH musí být kladné celé číslo."
	echo "				Pokud není parametr WIDTH uveden, řídí se šířky řádků požadavky uvedenými níže."
	echo "					-d DISTRICT_FILE — pro příkaz districts vypisuje místo LAU 1 kódu okresu jeho jméno. Mapování kódů na jména je v souboru DISTRICT_FILE"
	echo "					-r REGIONS_FILE — pro příkaz regions vypisuje místo NUTS 3 kódu kraje jeho jméno. Mapování kódů na jména je v souboru REGIONS_FILE"
	echo ""

	echo "Seznam dostupných příkazů:"
	echo ""
	echo "	infected		Spočítá počet nakažených"
	echo "	merge			Sloučí několik souborů se záznamy do jednoho, zachovávající původní pořadí (hlavička bude ve výstupu jen jednou)"
	echo "	gender			Vypíše počet nakažených pro jednotlivá pohlaví"
	echo "	age			Vypíše statistiku počtu nakažených osob dle věku"
	echo "	daily			Vypíše statistiku nakažených osob pro jednotlivé dny"
	echo "	monthly			Vypíše statistiku nakažených osob pro jednotlivé měsíce"
	echo "	yearly			Vypíše statistiku nakažených osob pro jednotlivé roky"
	echo "	countries		Vypíše statistiku nakažených osob pro jednotlivé země nákazy (bez ČR, tj. kódu cz)"
	echo "	districts		Vypíše statistiku nakažených osob pro jednotlivé okresy"
	echo "	regions			Vypíše statistiku nakažených osob pro jednotlivé kraje"
	echo ""
	echo ""

	echo "Error Codes"
	echo ""
	echo "	0			Program skončil bez chyby"
	echo "	1			Program se ukončil z důvodu výskytu chyby, výstup je doprovázen patřičným chybovým hlášením"
	echo ""
	exit 0
}




########	ERROR SECTION	########

errorDate(){
	echo "Invalid date on filter \"$1\"!" >&2
	exit 1
}
errorDateSpec(){
	echo "Wrong date format (YYYY-MM-DD) on filter \"$1\" / date not specified!" >&2
	exit 1
}
errorMultipleFilter(){
	echo "Multiple usage of same filter \"$1\"!" >&2
	exit 1
}
errorGender(){
	echo "Filter \"$1\" has to be M / Z!" >&2
	exit 1
}
errorMultipleCommand(){
	echo "You cannot enter more than 1 COMMAND!" >&2
	exit 1
}

errorFilterWithoutFile(){
	echo "File not specified!" >&2
	exit 1
}

########	VARIABLES	########

afterTime="0000-01-01"
atCount=0

beforeTime="9999-12-31"
btCount=0

genderCount=0
gender="none"

termInput="cat -"

command="default"
cmdCount=0

newLine=$(printf "\r\n")

filters="0000"

head="id,datum,vek,pohlavi,kraj_nuts_kod,okres_lau_kod,nakaza_v_zahranici,nakaza_zeme_csu_kod,reportovano_khs"
header=0

########	Validation	########
validateGender(){	
	if [ $genderCount -eq 1 ]; then
			errorMultipleFilter "$1"
	fi
	genderCount=$((genderCount+1))
	if [ "$2" = "M" ]; then
		gender="$2"
		#echo "Gender is: \"$gender\""
		return 0
	elif [ "$2" = "Z" ]; then
		gender="$2"
		#echo "Gender is: \"$gender\""
		return 0
	else
		errorGender "$1"
	fi	
}

validateCommand(){
	if [ $cmdCount -eq 1 ]; then
		errorMultipleCommand
	fi
	cmdCount=$((cmdCount+1))
}

validateDate(){
	if [ "$1" = "-a" ]; then
		if [ $atCount -eq 1 ]; then
				errorMultipleFilter "$1"
		fi
	elif [ "$1" = "-b" ]; then 
		if [ $btCount -eq 1 ]; then
				errorMultipleFilter "$1"
		fi
	fi
	if expr "$2" : "^[0-9][0-9][0-9][0-9]\-[0-9][0-9]\-[0-9][0-9]">/dev/null; then
			# Year Validation
			$(echo $2 | awk -F \- '$1 == 0 {exit 1}') # This depends if gregorian calendar 1582 is counted
			if [ $? -eq 0 ]; then
				# Month Validation
				$(echo $2 | awk -F \- '$2 > 12 || $2 <= 0{exit 1}')
				if [ $? -eq 0 ]; then
					# Day Validation
					$(echo $2 | awk -F \- '{
						if($2 == 1 && ($3 > 31 || $3 <= 0)){
							exit 1
						}
						else if ($2 == 2 && ($1 % 4) != 0 && ($3 > 28 || $3 <= 0)){
							exit 1
						} 
						else if ($2 == 2 && ($1 % 4) == 0 && ($3 > 29 || $3 <= 0)){
							exit 1
						}
						else if($2 == 3 && ($3 > 31 || $3 <= 0)){
							exit 1
						}
						else if($2 == 4 && ($3 > 30 || $3 <= 0)){
							exit 1
						}
						else if($2 == 5 && ($3 > 31 || $3 <= 0)){
							exit 1
						}
						else if($2 == 6 && ($3 > 30 || $3 <= 0)){
							exit 1
						}
						else if($2 == 7 && ($3 > 31 || $3 <= 0)){
							exit 1
						}
						else if($2 == 8 && ($3 > 31 || $3 <= 0)){
							exit 1
						}
						else if($2 == 9 && ($3 > 30 || $3 <= 0)){
							exit 1
						}
						else if($2 == 10 && ($3 > 31 || $3 <= 0)){
							exit 1
						}
						else if($2 == 11 && ($3 > 30 || $3 <= 0)){
							exit 1
						}
						else if($2 == 12 && ($3 > 31 || $3 <= 0)){
							exit 1
						}
						
						}')
					if [ $? -eq 0 ]; then
						if [ "$1" = "-a" ]; then
							atCount=$((atCount+1))
							return 0
						else
							btCount=$((btCount+1))	
							return 0
						fi				
					else	
						errorDate "$1"
					fi
				else
					errorDate "$1"
				fi
			else
				errorDate "$1"
			fi
		else
			errorDateSpec "$1"
		fi
}

pickCommand(){
	case "$1" in
		"infected") if [ $genderCount -eq 1 ]; then
						filtered=$(echo "$logs" | awk -F ',' -v Af="$afterTime" -v Bf="$beforeTime" -v Ge="$gender" '$2 >= Af && $2 <= Bf && $4 == Ge {count[0]++} END{print count[0]}' )
						echo "$filtered"

					else
						filtered=$(echo "$logs" | awk -F ',' -v Af="$afterTime" -v Bf="$beforeTime" '$2 >= Af && $2 <= Bf {count[0]++} END{print count[0]}' )
						echo "$filtered"
					fi;;
		"merge") 
				if [ $genderCount -eq 1 ]; then
					filtered=$(echo "$logs" | awk -F ',' -v Af="$afterTime" -v Bf="$beforeTime" -v Ge="$gender" '$2 >= Af && $2 <= Bf && $4 == Ge {print $0}' )
					echo "$head"
					echo "$filtered"

				else
					filtered=$(echo "$logs" | awk -F ',' -v Af="$afterTime" -v Bf="$beforeTime" '$2 >= Af && $2 <= Bf {print $0}' )
					echo "$head"
					echo "$filtered"
				fi;;
		"gender")
				if [ $genderCount -eq 1 ]; then
					filtered=$(echo "$logs" | awk -F ',' -v Af="$afterTime" -v Bf="$beforeTime" -v Ge="$gender" '$2 >= Af && $2 <= Bf && $4 == Ge {count[0]++} END{print count[0]}' )
					if [ "$gender" = "M" ]; then
						echo "M: $filtered"
						echo "Z: 0"
					else
						echo "M: 0"
						echo "Z: $filtered"	
					fi

				else
					filtered=$(echo "$logs" | awk -F ',' -v Af="$afterTime" -v Bf="$beforeTime" '$2 >= Af && $2 <= Bf && $4 == "M" {count[0]++} END{print count[0]}' )
					if expr "$filtered" : "[1-9]*">/dev/null; then
						echo "M: $filtered"
					else
						echo "M : 0"
					fi
					filtered=$(echo "$logs" | awk -F ',' -v Af="$afterTime" -v Bf="$beforeTime" '$2 >= Af && $2 <= Bf && $4 == "Z" {count[0]++} END{print count[0]}' )
					if expr "$filtered" : "[1-9]*">/dev/null; then
						echo "Z: $filtered"
					else
						echo "Z : 0"
					fi

					filtered=$(echo "$logs" | awk -F ',' -v Af="$afterTime" -v Bf="$beforeTime" '$2 >= Af && $2 <= Bf && ($4 != "Z" && $4 != "M") {count[0]++} END{print count[0]}' )
					if expr "$filtered" : "[1-9]*">/dev/null; then
						echo "None: $filtered"
					fi
				fi;;
		"age")
				if [ $genderCount -eq 1 ]; then
						#0-5
					filtered=$(echo "$logs" | awk -F, -v Ge="$gender" -v Af="$afterTime" -v Bf="$beforeTime" '$3 >= 0 && $3 <= 5 && $4 == Ge && ($2 >= Af && $2 <= Bf) ' |  cut -d, -f3 | sort | uniq -c | awk '{countAge[0]+=$1} END {print countAge[0]}' )
						if expr "$filtered" : "[1-9]*">/dev/null; then
							echo "0-5	: $filtered"
						else
							echo "0-5	: 0"
						fi
					#6-105
					for i in 6 16 26 36 46 56 66 76 86 96; do
						filtered=$(echo "$logs" | awk -F, -v Ge="$gender" -v startIndex="$i" -v endIndex="$((i+9))" -v Af="$afterTime" -v Bf="$beforeTime" '$3 >= startIndex && $3 <= endIndex && $4 == Ge && ($2 >= Af && $2 <= Bf)' |  cut -d, -f3 | sort | uniq -c | awk '{countAge[0]+=$1} END {print countAge[0]}' )
						
						if expr "$filtered" : "[1-9]*">/dev/null; then
							echo "$i-$((i+9))	: $filtered"
						else
							echo "$i-$((i+9))	: 0"
						fi
					done
					#106+
					filtered=$(echo "$logs" | awk -F, -v Ge="$gender" -v Af="$afterTime" -v Bf="$beforeTime" '$3 >= 106 && $3 <= 10000000 && $4 == Ge && ($2 >= Af && $2 <= Bf)' |  cut -d, -f3 | sort | uniq -c | awk '{countAge[0]+=$1} END {print countAge[0]}' )	
						if expr "$filtered" : "[1-9]*">/dev/null; then
							echo ">105	: $filtered"
						else
							echo ">105	: 0"
						fi
					
					#None
					echo "None	: 0"
				else
					#0-5
					filtered=$(echo "$logs" | awk -F, -v Af="$afterTime" -v Bf="$beforeTime" '$3 >= 0 && $3 <= 5 && $2 >= Af && $2 <= Bf' |  cut -d, -f3 | sort | uniq -c | awk '{countAge[0]+=$1} END {print countAge[0]}' )
						if expr "$filtered" : "[1-9]*">/dev/null; then
							echo "0-5	: $filtered"
						else
							echo "0-5	: 0"
						fi
					#6-105
					for i in 6 16 26 36 46 56 66 76 86 96; do
						filtered=$(echo "$logs" | awk -F, -v startIndex="$i" -v endIndex="$((i+9))" -v Af="$afterTime" -v Bf="$beforeTime" '$3 >= startIndex && $3 <= endIndex && ($2 >= Af && $2 <= Bf)' |  cut -d, -f3 | sort | uniq -c | awk '{countAge[0]+=$1} END {print countAge[0]}' )
						if expr "$filtered" : "[1-9]*">/dev/null; then
							echo "$i-$((i+9))	: $filtered"
						else
							echo "$i-$((i+9))	: 0"
						fi
					done
					#106+
					filtered=$(echo "$logs" | awk -F, -v Af="$afterTime" -v Bf="$beforeTime" '$3 >= 106 && $3 <= 10000000 && ($2 >= Af && $2 <= Bf)' |  cut -d, -f3 | sort | uniq -c | awk '{countAge[0]+=$1} END {print countAge[0]}' )	
						if expr "$filtered" : "[1-9]*">/dev/null; then
							echo ">105	: $filtered"
						else
							echo ">105	: 0"
						fi
					
					#None
					filtered=$(echo "$logs" | awk -F, -v Af="$afterTime" -v Bf="$beforeTime" '($3 < 0 || $3 > 10000000) && $2 >= Af && $2 <= Bf' |  cut -d, -f3 | sort | uniq -c | awk '{countAge[0]+=$1} END {print countAge[0]}' )	
					if expr "$filtered" : "[1-9]*">/dev/null; then
						echo "None	: $filtered"
					else
						echo "None	: 0"
					fi
				fi;;
	esac

}

########	Control Code	########


while [ $# -gt 0 ]; do
	option="$1"

      case "$option" in
    "-h")	help; shift;;
	"-a")	
		afterTime="$2"
		validateDate "$1" "$2"
		shift
		shift;;
		
	"-b")	
		beforeTime="$2"
		validateDate "$1" "$2"
		shift
		shift;;

	"-g")
		validateGender "$1" "$2"
		shift
		shift;;

	"infected" | "merge" | "gender" | "age" | "daily" | "monthly" | "yearly" | "countries" | "districts" | "regions")
		command="$1"
		validateCommand
		shift;;

   	*)

		if expr "$1" : "^\-[aA-zZ]">/dev/null; then #If $1 is a non-existing filter
           if [ $? -eq 0 ]; then
                echo "Invalid filter \"$1\"">&2
				exit 1
        	fi

        elif expr "$1" : "[aA-zZ]*">/dev/null; then	#If $1 is expected to be a file
           	if [ $? -eq 0 ]; then
			   	if [[ "$1" =~ ^.*(.gz)$ ]]; then
					logs="$logs$(gzip -d -c "$1" | awk -F , 'NR>1')$newLine"
					#echo "$logs"
				else
					logs="$logs$(cat "$1" | awk -F , -v header="$head" 'NR>0{if($0 == "header"){next}else{print $0}}')$newLine"

			   fi
				
				shift
			
				if [ $# -eq 0 ]; then
				#echo "id,datum,vek,pohlavi,kraj_nuts_kod,okres_lau_kod,nakaza_v_zahranici,nakaza_zeme_csu_kod,reportovano_khs"
					if [ "$command" = "default" ]; then
						command="merge"			
						pickCommand "$command"
					else
						pickCommand "$command"	
						

					fi
				fi
			fi
        fi;;
      esac
done

if [ "$logs" = "" ]; then
	logs="$logs$(cat - | awk -F , 'NR>1')$newLine"
	if [ "$command" = "default" ]; then
		command="merge"			
		pickCommand "$command"
	else
		pickCommand "$command"	
	fi
fi



